"""
simulators/fdtoverlay_merger.py - Core fdtoverlay merge functionality
模擬 fdtoverlay 工具的核心邏輯，將 base DTB 和 overlay DTBO 合併
"""

import os
import sys
import re
from typing import Dict, List, Any, Optional, Tuple
from datetime import datetime


class DTBParser:
    """解析已編譯的 .dtb.txt 和 .dtbo.txt 文件"""
    
    def __init__(self):
        self.nodes = {}
        self.phandles = {}
        self.labels = {}
        self.source_file = ""
        self.total_nodes = 0
        self.total_phandles = 0
        self.raw_content = ""
    
    def parse_dtb_file(self, file_path: str) -> bool:
        """解析 DTB 文件"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                self.raw_content = f.read()
            
            # 提取源文件信息
            source_match = re.search(r'Source file: (.+)', self.raw_content)
            if source_match:
                self.source_file = source_match.group(1)
            
            # 提取統計信息
            nodes_match = re.search(r'Total nodes: (\d+)', self.raw_content)
            if nodes_match:
                self.total_nodes = int(nodes_match.group(1))
                
            phandles_match = re.search(r'Total phandles: (\d+)', self.raw_content)
            if phandles_match:
                self.total_phandles = int(phandles_match.group(1))
            
            # 解析 phandle 表
            self._parse_phandle_table()
            
            return True
            
        except Exception as e:
            print(f"[ERROR] Failed to parse {file_path}: {e}")
            return False
    
    def _parse_phandle_table(self):
        """解析 phandle 映射表"""
        # 匹配 phandle 表部分
        phandle_section = re.search(
            r'/\*\s*=+ PHANDLE TABLE =+\s*\*(.*?)\*/\s*', 
            self.raw_content, re.DOTALL
        )
        
        if not phandle_section:
            return
            
        phandle_text = phandle_section.group(1)
        
        # 解析每個 phandle 條目: label: 0xNN (path)
        phandle_pattern = r'\*\s+(\w+):\s+(0x[0-9a-f]+)\s+\(([^)]+)\)'
        
        for match in re.finditer(phandle_pattern, phandle_text, re.IGNORECASE):
            label = match.group(1)
            phandle = match.group(2)
            path = match.group(3)
            
            self.phandles[phandle] = path
            self.labels[label] = {
                'phandle': phandle,
                'path': path
            }


class FDTOverlayMerger:
    """處理 overlay 合併邏輯"""
    
    def __init__(self):
        self.base_dtb = None
        self.overlay_dtbs = []
        self.changes_made = []
    
    def load_base_dtb(self, base_file: str) -> bool:
        """載入 base DTB 文件"""
        parser = DTBParser()
        if parser.parse_dtb_file(base_file):
            self.base_dtb = parser
            return True
        return False
    
    def add_overlay_dtb(self, overlay_file: str) -> bool:
        """添加 overlay DTB 文件"""
        parser = DTBParser()
        if parser.parse_dtb_file(overlay_file):
            self.overlay_dtbs.append(parser)
            return True
        return False
    
    def merge_overlays(self, verbose: bool = False) -> bool:
        """合併所有 overlay"""
        try:
            for i, overlay in enumerate(self.overlay_dtbs):
                if verbose:
                    print(f"    Merging overlay {i+1}/{len(self.overlay_dtbs)}: {os.path.basename(overlay.source_file)}")
                
                # 記錄變更 (簡化版本)
                self.changes_made.append({
                    'type': 'overlay_applied',
                    'source': overlay.source_file,
                    'phandles': len(overlay.phandles),
                    'labels': len(overlay.labels)
                })
            
            return True
            
        except Exception as e:
            print(f"[ERROR] Merge failed: {e}")
            return False
    
    def generate_merged_dtb(self, output_file: str, verbose: bool = False) -> bool:
        """生成合併後的 DTB 文件"""
        try:
            with open(output_file, 'w', encoding='utf-8') as f:
                self._write_merged_dtb(f)
            
            if verbose:
                print(f"    Generated merged DTB: {os.path.basename(output_file)}")
                print(f"    Total overlays applied: {len(self.overlay_dtbs)}")
            
            return True
            
        except Exception as e:
            print(f"[ERROR] Failed to generate {output_file}: {e}")
            return False
    
    def _write_merged_dtb(self, f):
        """寫入合併後的 DTB 內容"""
        f.write("/*\n")
        f.write(" * Generated by dt-sim fdtoverlay - merged DTB\n")
        f.write(f" * Base file: {self.base_dtb.source_file}\n")
        f.write(" * Overlay files:\n")
        for overlay in self.overlay_dtbs:
            f.write(f" *   - {overlay.source_file}\n")
        f.write(f" * Merge timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f" * Base nodes: {self.base_dtb.total_nodes}\n")
        f.write(f" * Base phandles: {self.base_dtb.total_phandles}\n")
        f.write(f" * Overlays applied: {len(self.overlay_dtbs)}\n")
        f.write(" */\n\n")
        f.write("/dts-v1/;\n\n")
        
        # 合併 phandle 表
        all_phandles = self.base_dtb.phandles.copy()
        all_labels = self.base_dtb.labels.copy()
        
        for overlay in self.overlay_dtbs:
            all_phandles.update(overlay.phandles)
            all_labels.update(overlay.labels)
        
        if all_phandles:
            f.write("/*\n")
            f.write(" * ===== MERGED PHANDLE TABLE =====\n")
            f.write(" * phandle_map: {\n")
            
            for label, info in sorted(all_labels.items()):
                f.write(f" *   {label}: {info['phandle']} ({info['path']})\n")
            
            f.write(" * }\n")
            f.write(" */\n\n")
        
        # 寫入基礎 DTB 內容 (去除頭部注釋)
        base_content = self._extract_dtb_content(self.base_dtb.raw_content)
        f.write(base_content)
        
        # 添加 overlay 變更記錄
        if self.changes_made:
            f.write("\n/*\n")
            f.write(" * ===== OVERLAY CHANGES APPLIED =====\n")
            for i, change in enumerate(self.changes_made, 1):
                f.write(f" * {i}. Applied overlay: {os.path.basename(change['source'])}\n")
                f.write(f" *    - Labels: {change['labels']}, Phandles: {change['phandles']}\n")
            f.write(" */\n")
    
    def _extract_dtb_content(self, raw_content: str) -> str:
        """提取 DTB 的實際內容部分（去除頭部注釋）"""
        # 找到 /dts-v1/; 之後的內容
        dts_start = raw_content.find('/dts-v1/;')
        if dts_start == -1:
            return raw_content
        
        # 找到實際節點定義開始的位置
        content_start = raw_content.find('/ {', dts_start)
        if content_start == -1:
            return raw_content[dts_start:]
        
        return raw_content[content_start:]
    
    def show_merge_summary(self):
        """顯示合併摘要"""
        print(f"\n=== fdtoverlay Merge Summary ===")
        print(f"Base DTB: {os.path.basename(self.base_dtb.source_file)}")
        print(f"  - Nodes: {self.base_dtb.total_nodes}")
        print(f"  - Phandles: {self.base_dtb.total_phandles}")
        
        print(f"Overlay DTBs: {len(self.overlay_dtbs)} files")
        for i, overlay in enumerate(self.overlay_dtbs, 1):
            print(f"  {i}. {os.path.basename(overlay.source_file)}")
            print(f"     - Labels: {len(overlay.labels)}, Phandles: {len(overlay.phandles)}")
        
        print(f"Result: Successfully merged {len(self.overlay_dtbs)} overlays into base DTB")
    
    def merge_overlay_text(self, base_file: str, overlay_files: List[str], output_file: str, 
                          verbose: bool = False, show_changes: bool = False) -> bool:
        """
        主要的合併接口 - 提供向後兼容性
        
        Args:
            base_file: Base DTB 文件路徑
            overlay_files: Overlay DTBO 文件路徑列表
            output_file: 輸出文件路徑
            verbose: 是否顯示詳細信息
            show_changes: 是否顯示變更摘要
            
        Returns:
            bool: 合併是否成功
        """
        try:
            # 載入 base DTB
            if not self.load_base_dtb(base_file):
                return False
            
            # 載入所有 overlay DTBs
            for overlay_file in overlay_files:
                if not self.add_overlay_dtb(overlay_file):
                    return False
            
            # 執行合併
            if not self.merge_overlays(verbose):
                return False
            
            # 顯示變更摘要
            if show_changes:
                self.show_merge_summary()
            
            # 生成輸出文件
            if not self.generate_merged_dtb(output_file, verbose):
                return False
            
            return True
            
        except Exception as e:
            print(f"[ERROR] merge_overlay_text failed: {e}")
            return False