"""
generators/dtb_text_generator.py - DTB Text Format Generator

Generates human-readable DTB text format from Intermediate Representation.
Works directly with IR for optimal performance and clean architecture.
"""

from typing import List
from core.intermediate import IntermediateRepresentation, IRNode, IRProperty
from core.ast import Value, ValueType, Reference


class DTBTextGenerator:
    """Generate DTB text format from intermediate representation"""
    
    def __init__(self, verbose: bool = False):
        self.verbose = verbose
    
    def generate_from_ir(self, ir: IntermediateRepresentation, output_file: str, source_file: str = "") -> None:
        """Generate DTB text format from IR and write to file"""
        lines = []
        
        # File header
        lines.append("/*")
        lines.append(" * Generated by dt-sim dtc")
        if source_file:
            lines.append(f" * Source: {source_file}")
        lines.append(" */")
        lines.append("")
        lines.append("/dts-v1/;")
        lines.append("")
        
        # Generate device tree content directly from IR (overrides already merged)
        if ir.root:
            lines.extend(self._generate_ir_node_text(ir.root, 0))
        
        # Write to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        
        if self.verbose:
            print(f"Generated DTB text from IR: {output_file}")
    
    # Legacy method for backward compatibility
    def generate(self, tree, output_file: str, source_file: str = "") -> None:
        """Legacy method - converts AST to IR then generates"""
        from core.intermediate import IRBuilder
        
        ir_builder = IRBuilder(verbose=self.verbose)
        ir = ir_builder.build_from_ast(tree)
        
        self.generate_from_ir(ir, output_file, source_file)
    
    # ===== IR-BASED TEXT GENERATION METHODS =====
    
    def _generate_ir_node_text(self, node: IRNode, indent_level: int) -> List[str]:
        """Generate text lines for an IR node"""
        lines = []
        indent = "    " * indent_level
        
        # Handle root node specially
        if node.name == "/" and indent_level == 0:
            # Root node
            labels_str = f"{node.label}: " if node.label else ""
            lines.append(f"{labels_str}/ {{")
            
            # Properties of root
            for prop in node.properties:
                lines.extend(self._generate_ir_property_text(prop, indent_level + 1))
            
            # Child nodes
            if node.children:
                for child in node.children:
                    lines.append("")  # Blank line before each child
                    lines.extend(self._generate_ir_node_text(child, indent_level + 1))
            
            lines.append("};")
            return lines
        else:
            # Normal node
            labels_str = f"{node.label}: " if node.label else ""
            lines.append(f"{indent}{labels_str}{node.full_name} {{")
        
        # Properties
        for prop in node.properties:
            lines.extend(self._generate_ir_property_text(prop, indent_level + 1))
        
        # Child nodes
        if node.children:
            if node.properties:  # Add blank line between properties and children
                lines.append("")
            for child in node.children:
                lines.extend(self._generate_ir_node_text(child, indent_level + 1))
                lines.append("")  # Blank line after each child
        
        lines.append(f"{indent}}};")
        return lines
    
    def _generate_ir_property_text(self, prop: IRProperty, indent_level: int) -> List[str]:
        """Generate text lines for an IR property"""
        lines = []
        indent = "    " * indent_level
        
        if prop.is_boolean:
            # Boolean property (no value)
            lines.append(f"{indent}{prop.name};")
        else:
            # Property with values
            value_strs = []
            for value in prop.values:
                value_strs.append(self._format_ir_property_value(value))
            
            if len(value_strs) == 1:
                lines.append(f"{indent}{prop.name} = {value_strs[0]};")
            else:
                lines.append(f"{indent}{prop.name} = {', '.join(value_strs)};")
        
        return lines
    
    def _format_ir_property_value(self, value: Value) -> str:
        """Format a single IR property value correctly"""
        if value.type == ValueType.STRING:
            return f'"{value.data}"'
        elif value.type == ValueType.NUMBER:
            return f"0x{value.data:x}" if value.data > 9 else str(value.data)
        elif value.type == ValueType.CELL_LIST:
            # Format as <value1 value2 ...>
            cells = []
            for item in value.data:
                if isinstance(item, Reference):
                    cells.append(str(item))
                elif isinstance(item, str):
                    # Handle identifiers like IMX95_PAD_CCM_CLKO2__GPIO3_IO_BIT27
                    cells.append(item)
                else:
                    cells.append(f"0x{item:x}" if item > 9 else str(item))
            return f"<{' '.join(cells)}>"
        elif value.type == ValueType.BYTE_STREAM:
            # Format as [byte1 byte2 ...]
            bytes_str = ' '.join(f"{b:02x}" for b in value.data)
            return f"[{bytes_str}]"
        elif value.type == ValueType.REFERENCE:
            # Format standalone reference
            return str(value.data)
        elif value.type == ValueType.BOOLEAN:
            # Boolean values should not be formatted with = assignment
            return ""
        else:
            return str(value.data)
