"""
utils/text_generator.py - 文本生成器
將設備樹轉換為可讀格式
"""

from typing import List

# ✅ 修復導入 - 從正確的 core 模組導入
try:
    from core import DeviceTree, DTSNode, DTSProperty
except ImportError:
    # 如果 core 模組不可用，定義最小接口
    print("Warning: core module not found in text_generator")
    
    class DeviceTree:
        def __init__(self):
            self.root = None
            
        def get_all_nodes(self):
            return []
    
    class DTSNode:
        def __init__(self):
            self.name = ""
            self.labels = []
            self.properties = {}
            self.children = {}
            
        def get_path(self):
            return "/"
    
    class DTSProperty:
        def __init__(self):
            self.name = ""
            self.type = ""
            self.value = None
            self.raw_value = ""


class TextGenerator:
    """文本生成器 - 將設備樹轉換為可讀格式"""
    
    def generate_dtb_text(self, device_tree: DeviceTree, output_file: str):
        """生成 DTB 文本格式"""
        lines = []
        
        # 文件頭部註解
        lines.append("/*")
        lines.append(" * Generated by dt-sim dtc")
        lines.append(" */")
        lines.append("")
        lines.append("/dts-v1/;")
        lines.append("")
        
        # 生成設備樹內容
        if device_tree.root:
            lines.extend(self._generate_node_lines(device_tree.root, 0))
        
        # 寫入文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    def generate_dtbo_text(self, overlay, output_file: str):
        """生成 DTBO 文本格式"""
        lines = []
        
        # 文件頭部註解
        lines.append("/*")
        lines.append(" * Generated by dt-sim overlay")
        lines.append(" */")
        lines.append("")
        lines.append("/dts-v1/;")
        lines.append("/plugin/;")
        lines.append("")
        
        # 生成 overlay 內容
        if hasattr(overlay, 'fragments'):
            for i, fragment in enumerate(overlay.fragments):
                lines.append(f"fragment@{i} {{")
                if hasattr(fragment, 'target_path'):
                    lines.append(f'    target-path = "{fragment.target_path}";')
                elif hasattr(fragment, 'target_label'):
                    lines.append(f"    target = <&{fragment.target_label}>;")
                lines.append("    __overlay__ {")
                # 添加 overlay 內容
                lines.append("    };")
                lines.append("};")
        
        # 寫入文件
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    def _generate_node_lines(self, node: DTSNode, indent_level: int) -> List[str]:
        """生成節點的文本行"""
        lines = []
        indent = "    " * indent_level
        
        # 節點開始
        labels_str = ": ".join(node.labels) + ": " if node.labels else ""
        if node.name == "/":
            lines.append(f"{labels_str}/ {{")
        else:
            lines.append(f"{indent}{labels_str}{node.name} {{")
        
        # 屬性
        for prop_name in sorted(node.properties.keys()):
            prop = node.properties[prop_name]
            if hasattr(prop, 'type') and prop.type == "empty":
                lines.append(f"{indent}    {prop.name};")
            elif hasattr(prop, 'raw_value') and prop.raw_value:
                lines.append(f"{indent}    {prop.name} = {prop.raw_value};")
            elif hasattr(prop, 'value'):
                if isinstance(prop.value, str):
                    lines.append(f'{indent}    {prop.name} = "{prop.value}";')
                else:
                    lines.append(f"{indent}    {prop.name} = {prop.value};")
        
        # 子節點
        for child_name in sorted(node.children.keys()):
            child = node.children[child_name]
            lines.append("")
            lines.extend(self._generate_node_lines(child, indent_level + 1))
        
        lines.append(f"{indent}}};")
        
        return lines


# 向後兼容的別名
DTBTextGenerator = TextGenerator
DTBOTextGenerator = TextGenerator

__all__ = ['TextGenerator', 'DTBTextGenerator', 'DTBOTextGenerator']
