"""
utils/text_generator.py - Text Generator
Convert device tree to readable format
"""

from typing import List

# ✅ Fixed import - import from correct core module
try:
    from core import DeviceTree, DTSNode, DTSProperty
except ImportError:
    # If core module is not available, define minimal interface
    print("Warning: core module not found in text_generator")
    
    class DeviceTree:
        def __init__(self):
            self.root = None
            
        def get_all_nodes(self):
            return []
    
    class DTSNode:
        def __init__(self):
            self.name = ""
            self.labels = []
            self.properties = {}
            self.children = {}
            
        def get_path(self):
            return "/"
    
    class DTSProperty:
        def __init__(self):
            self.name = ""
            self.type = ""
            self.value = None
            self.raw_value = ""


class TextGenerator:
    """Text Generator - Convert device tree to readable format"""
    
    def generate_dtb_text(self, device_tree: DeviceTree, output_file: str, source_file: str = ""):
        """Generate DTB text format"""
        lines = []
        
        # File header comment
        lines.append("/*")
        lines.append(" * Generated by dt-sim dtc")
        lines.append(" */")
        lines.append("")
        lines.append("/dts-v1/;")
        lines.append("")
        
        # Generate device tree content
        if device_tree.root:
            lines.extend(self._generate_node_lines(device_tree.root, 0))
        
        # Write file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    def generate_dtbo_text(self, overlay, output_file: str):
        """Generate DTBO text format"""
        lines = []
        
        # File header comment
        lines.append("/*")
        lines.append(" * Generated by dt-sim overlay")
        lines.append(" */")
        lines.append("")
        lines.append("/dts-v1/;")
        lines.append("/plugin/;")
        lines.append("")
        
        # Generate overlay content
        if hasattr(overlay, 'fragments'):
            for i, fragment in enumerate(overlay.fragments):
                lines.append(f"fragment@{i} {{")
                if hasattr(fragment, 'target_path'):
                    lines.append(f'    target-path = "{fragment.target_path}";')
                elif hasattr(fragment, 'target_label'):
                    lines.append(f"    target = <&{fragment.target_label}>;")
                lines.append("    __overlay__ {")
                # Add overlay content
                lines.append("    };")
                lines.append("};")
        
        # Write file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
    
    def _generate_node_lines(self, node: DTSNode, indent_level: int) -> List[str]:
        """Generate text lines for node"""
        lines = []
        indent = "    " * indent_level
        
        # Node start
        labels_str = ": ".join(node.labels) + ": " if node.labels else ""
        if node.name == "/":
            lines.append(f"{labels_str}/ {{")
        else:
            lines.append(f"{indent}{labels_str}{node.name} {{")
        
        # Properties
        for prop_name in sorted(node.properties.keys()):
            prop = node.properties[prop_name]
            if hasattr(prop, 'type') and prop.type == "empty":
                lines.append(f"{indent}    {prop.name};")
            elif hasattr(prop, 'raw_value') and prop.raw_value:
                lines.append(f"{indent}    {prop.name} = {prop.raw_value};")
            elif hasattr(prop, 'value'):
                if isinstance(prop.value, str):
                    lines.append(f'{indent}    {prop.name} = "{prop.value}";')
                else:
                    lines.append(f"{indent}    {prop.name} = {prop.value};")
        
        # Child nodes
        for child_name in sorted(node.children.keys()):
            child = node.children[child_name]
            lines.append("")
            lines.extend(self._generate_node_lines(child, indent_level + 1))
        
        lines.append(f"{indent}}};")
        
        return lines


# Backward compatible aliases
DTBTextGenerator = TextGenerator
DTBOTextGenerator = TextGenerator

__all__ = ['TextGenerator', 'DTBTextGenerator', 'DTBOTextGenerator']
